language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
install:
  - yarn install
  - npm install -g codecov
script:
  - yarn test
  - codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
