language: node_js
cache:
  directories:
    - ~/.npm
install:
  - yarn install
  - npm install -g codecov
script:
  - yarn test
  - codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
